### PR TITLE
units *Wh -> *W connect #12

### PR DESCRIPTION
**Pull request by scsirdx**

### CODE REVIEW

**Review by ChriWiChris — COMMENTED** [review]
Looks good. However I can't check it locally.
I am wondering what's happening if the user hits the "year" or "month" button: will there be also `kW` used as unit or does the algorithm switch to `kWh` then?

**Comment by scsirdx** [comment]
Hmm. 
So daily/hourly will be *W, and yearly/monthly *Wh ?

**Comment by ChriWiChris** [comment]
Exact.

**Comment by scsirdx** [comment]
Ok, i'll fix it.

**Review by ChriWiChris — APPROVED** [review]
Approved without testing locally. Code looks good to me.

**Pull request merged**
